bot/urls.py
from django.urls import path
from bot import views

urlpatterns = [
    path("list/", views.telegram_user_list, name="telegram-user-list"),
    path("data/list/", views.telegram_user_data_list, name="telegram-user-data-list"),
    path("<int:pk>/activation/", views.telegram_user_activation, name="telegram-user-activation"),
    path("<int:pk>/detail/", views.telegram_user_detail, name="telegram-user-detail"),
]

category/urls.py
from django.urls import path
from category import views

urlpatterns = [
    path("list/", views.category_list, name="category-list"),
    path("create/", views.category_create, name="category-create"),
    path("<int:pk>/edit/", views.category_edit, name="category-edit"),
    path("<int:pk>/delete/", views.category_delete, name="category-delete"),
]

core/urls.py
from django.conf.urls import include
from django.urls import path
from core import views
from category import urls as category_urls
from product import urls as product_urls
from bot import urls as telegram_user_urls
from order import urls as order_urls

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("login/", views.dashboard_login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("category/", include(category_urls)),
    path("product/", include(product_urls)),
    path("telegram-user/", include(telegram_user_urls)),
    path("order/", include(order_urls)),
]

fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

urlpatterns = [
    path("list/", views.order_list, name="order-list"),
    path("<int:pk>/edit/", views.order_edit, name="order-edit"),
    path("<int:pk>/chat/", views.order_chat, name="order-chat"),
    path("<int:pk>/map/", views.order_map, name="order-map"),
]

product/urls.py
from django.urls import path
from product import views

urlpatterns = [
    path("list/", views.product_list, name="product-list"),
    path("create/", views.product_create, name="product-create"),
    path("<int:pk>/edit/", views.product_edit, name="product-edit"),
    path("<int:pk>/delete/", views.product_delete, name="product-delete"),
]

templates/_partials/footer.html
{% load static %}
<footer class="footer pt-3  ">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-sm text-muted text-lg-start">
                    ©
                    <script>
          document.write(new Date().getFullYear())


                    </script>
                    ,
                    made with <i class="fa fa-heart"></i> by
                    <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative
                        Tim</a>
                    for a better web.
                </div>
            </div>
            <div class="col-lg-6">
                <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative
                            Tim</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted"
                           target="_blank">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted"
                           target="_blank">License</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/_partials/navbar.html
{% load static %}
<nav class="navbar navbar-main navbar-expand-lg  px-0 mx-4 shadow-none border-radius-xl z-index-sticky" id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            {% url 'dashboard:dashboard' as dashboard_url %}
            {% url 'dashboard:category-list' as category_url %}
            {% url 'dashboard:category-create' as category_create_url %}
            {% url 'dashboard:category-edit' pk=model.id as category_edit_url %}
            {% url 'dashboard:product-list' as product_url %}
            {% url 'dashboard:product-create' as product_create_url %}
            {% url 'dashboard:product-edit' pk=model.id as product_edit_url %}
            {% url 'dashboard:order-list' as order_url %}
            {% url 'dashboard:order-edit' pk=model.id as order_edit_url %}
            {% url 'dashboard:telegram-user-list' as telegram_user_list_url %}
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm">
                    <a class="text-white" href="javascript:;">
                        <i class="ni ni-box-2"></i>
                    </a>
                </li>
                <li class="breadcrumb-item text-sm text-white"><a class="opacity-5 text-white" href="javascript:;"> Sahifalar </a>
                </li>
                <li class="breadcrumb-item text-sm text-white active" aria-current="page">
                    {% if request.path == dashboard_url %}
                        Dashboard
                    {% elif request.path == category_url or request.path == category_create_url or request.path == category_edit_url %}
                        Kategoriyalar
                    {% elif request.path == product_url or request.path == product_create_url or request.path == product_edit_url %}
                        Mahsulotlar
                    {% elif request.path == order_url %}
                        Buyurtmalar
                    {% elif request.path == telegram_user_list_url %}
                        Foydalanuvchilar
                    {% endif %}
                </li>
            </ol>
            <h6 class="font-weight-bolder mb-0 text-white">
                {% if request.path == dashboard_url %}
                Dashboard
                {% elif request.path == category_url %}
                Kategoriyalar royxati
                {% elif request.path == category_create_url %}
                Kategoriya qo'shish
                {% elif request.path == category_edit_url %}
                Kategoriyani o'zgartirish
                {% elif request.path == product_url %}
                Mahsulotlar royxati
                {% elif request.path == product_create_url %}
                Mahsulot qo'shish
                {% elif request.path == product_edit_url %}
                Mahsulotni o'zgartirish
                {% elif request.path == order_url %}
                Buyurtmalar royxati
                {% elif request.path == order_edit_url %}
                Buyurtmani o'zgartirish
                {% elif request.path == telegram_user_list_url %}
                Foydalanuvchilar royxati
                {% endif %}
            </h6>
        </nav>
        <div class="sidenav-toggler sidenav-toggler-inner d-xl-block d-none ">
            <a href="javascript:;" class="nav-link p-0">
                <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line bg-white"></i>
                    <i class="sidenav-toggler-line bg-white"></i>
                    <i class="sidenav-toggler-line bg-white"></i>
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            </div>
            <ul class="navbar-nav  justify-content-end">
                <li class="nav-item d-flex align-items-center" id="logout">
                    <i class="fas fa-power-off me-sm-1 text-danger"></i>
                    <span class="d-sm-inline d-none text-danger"> Chiqish </span>
                </li>
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/_partials/sidebar.html
{% load static %}
{% load custom_filters %}
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4"
       id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="/" target="_blank">
            <img src="{% static 'img/fast-food-icon.png' %}" class="navbar-brand-img h-100 mb-2" alt="main_logo">
            <span class="ms-3 font-weight-bold"  style="font-size:120%;">Hot Kebab</span>
        </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto h-auto h-100" id="sidenav-collapse-main">
        {% if user.is_superuser %}
        <ul class="navbar-nav">
            <li class="nav-item">
                {% url 'dashboard:dashboard' as dashboard_url %}
                <a class="nav-link {% if request.path == dashboard_url %}active{% endif %}" href="{{ dashboard_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="ni ni-shop text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-2">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'dashboard:category-list' as category_url %}
                <a class="nav-link {% if request.path|startswith:'/category/' %}active{% endif %}" href="{{ category_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="fas fa-stream text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1 mt-1"> Kategoriyalar </span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'dashboard:product-list' as product_url %}
                <a class="nav-link {% if request.path|startswith:'/product/' %}active{% endif %}" href="{{ product_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="fas fa-hamburger text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1 mt-1"> Mahsulotlar </span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'dashboard:order-list' as order_url %}
                <a class="nav-link {% if request.path|startswith:'/order/' %}active{% endif %}" href="{{ order_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="fas fa-clipboard-list text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1 mt-1"> Buyurtmalar </span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'dashboard:telegram-user-list' as telegram_user_list_url %}
                <a class="nav-link {% if request.path|startswith:'/telegram-user/' %}active{% endif %}" href="{{ telegram_user_list_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="fas fa-users text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1 mt-1"> Foydalanuvchilar </span>
                </a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                {% url 'dashboard:dashboard' as dashboard_url %}
                <a class="nav-link {% if request.path == dashboard_url %}active{% endif %}" href="{{ dashboard_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="ni ni-shop text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-2">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'dashboard:order-list' as order_url %}
                <a class="nav-link {% if request.path|startswith:'/order/' %}active{% endif %}" href="{{ order_url }}">
                    <div class="icon icon-shape icon-sm text-center d-flex align-items-center justify-content-center">
                        <i class="fas fa-clipboard-list text-success text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1 mt-1"> Buyurtmalar </span>
                </a>
            </li>
        </ul>
        {% endif %}
    </div>
</aside>