bot/urls.py
from django.urls import path
from bot import views

urlpatterns = [
    path("list/", views.telegram_user_list, name="telegram-user-list"),
    path("data/list/", views.telegram_user_data_list, name="telegram-user-data-list"),
    path("<int:pk>/activation/", views.telegram_user_activation, name="telegram-user-activation"),
    path("<int:pk>/detail/", views.telegram_user_detail, name="telegram-user-detail"),
]

category/urls.py
from django.urls import path
from category import views

urlpatterns = [
    path("list/", views.category_list, name="category-list"),
    path("create/", views.category_create, name="category-create"),
    path("<int:pk>/edit/", views.category_edit, name="category-edit"),
    path("<int:pk>/delete/", views.category_delete, name="category-delete"),
]

core/urls.py
from django.conf.urls import include
from django.urls import path
from core import views
from category import urls as category_urls
from product import urls as product_urls
from bot import urls as telegram_user_urls
from order import urls as order_urls

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("login/", views.dashboard_login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("category/", include(category_urls)),
    path("product/", include(product_urls)),
    path("telegram-user/", include(telegram_user_urls)),
    path("order/", include(order_urls)),
]

fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    order = models.SmallIntegerField(default=1)
    parent = models.ForeignKey("self", null=True, on_delete=models.SET_NULL)
    is_active = models.BooleanField()

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"

category/forms.py
from category.models import Category
from django import forms


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ("parent", )
        labels = {
            "name": "Nomi",
            "order": "Tartib raqami",
            "is_active": "Faolmi",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "order": forms.NumberInput(attrs={"class": "form-control"}),
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

    def save(self, commit=True, *args, **kwargs):
        model = super().save(commit=False)
        if commit:
            model.save()
        return model

category/views.py
from django.template.response import TemplateResponse
from category.models import Category
from category.forms import CategoryForm
from django.shortcuts import redirect, get_object_or_404, reverse
from core.views import login_required, check_users_permissions
from django.http import JsonResponse


@login_required
@check_users_permissions(only_superuser=True)
def category_list(request):
    categories = Category.objects.all().order_by("order")
    context = {
        "categories": categories
    }
    return TemplateResponse(request, "category/list.html", context)


@login_required
@check_users_permissions(only_superuser=True)
def category_create(request):
    model = None
    form = CategoryForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect("dashboard:category-list")
        else:
            print(form.errors)
    context = {
        "model": model,
        "form": form
    }
    return TemplateResponse(request, "category/form.html", context)


@login_required
@check_users_permissions(only_superuser=True)
def category_edit(request, pk=None):
    model = Category.objects.get(pk=pk)
    form = CategoryForm(request.POST or None, instance=model)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect("dashboard:category-list")
        else:
            print(form.errors)
    context = {
        "model": model,
        "form": form,
    }
    return TemplateResponse(request, "category/form.html", context)


@login_required
@check_users_permissions(only_superuser=True)
def category_delete(request, pk=None):
    model = get_object_or_404(Category, pk=pk)
    model.delete()
    return JsonResponse({"url": reverse("dashboard:category-list")})

templates/category/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="col-md-12">
                            <h5 class="">{% if model %}O'zgartirish {{ model.name }}{% else %}Kategoriya qo'shish{% endif %}</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" autocomplete=off enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        {{ form.name.errors }}
                                        <label class="form-control-label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.order.errors }}
                                        <label class="form-control-label" for="{{ form.order.id_for_label }}">{{ form.order.label }}</label>
                                        {{ form.order }}
                                    </div>
                                    <div class="form-check">
                                        {{ form.is_active.errors }}
                                        <label class="form-control-label" for="{{ form.is_active.id_for_label }}">{{ form.is_active.label }}</label>
                                        {{ form.is_active }}
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group text-left mb-0">
                                        {% if model %}
                                        <button class="btn btn-warning waves-effect waves-light mr-1" type="submit">
                                            Saqlash
                                        </button>
                                        {% else %}
                                        <button class="btn btn-success waves-effect waves-light mr-1" type="submit">
                                            Qo'shish
                                        </button>
                                        {% endif %}
                                        <a href="{% url 'dashboard:category-list' %}" class="btn btn-danger waves-effect waves-light">
                                            Bekor qilish
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/category/list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'js/plugins/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card p-3">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-10"><h5 class="mb-0">Kategoriyalar</h5></div>
                            <div class="col-md-1 mx-auto">
                                <a href="{% url 'dashboard:category-create' %}" class="btn btn-success mt-2"
                                   data-toggle="tooltip" data-original-title="Добавить">
                                    Qo'shish
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-flush" id="datatable-basic">
                                <thead class="thead-light">
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        ID
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Nomi
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Tartib raqami
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Status
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for category in categories %}
                                <tr>
                                    <td class="text-sm font-weight-normal"><div style="margin-left:1rem;">{{ category.id }}</div></td>
                                    <td class="text-sm text-center font-weight-normal">{{ category.name }}</td>
                                    <td class="text-sm text-center font-weight-normal">{{ category.order }}</td>
                                    <td class="text-sm text-center font-weight-normal">
                                        {% if category.is_active %}
                                        Aktiv
                                        {% else %}
                                        Aktiv emas
                                        {% endif %}
                                    </td>
                                    <td class="text-sm text-center font-weight-normal">
                                        <a href="{% url 'dashboard:category-edit' pk=category.id %}" class="badge badge-sm bg-gradient-warning font-weight-bold text-xs" data-toggle="tooltip" data-original-title="O'zgartirish">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="{% url 'dashboard:category-delete' pk=category.id %}" class="faq-delete badge badge-sm bg-gradient-danger font-weight-bold text-xs" data-toggle="tooltip" data-original-title="O'chirib tashlash">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
    $(".faq-delete").click(function(e){
        var access_url = $(this).attr('href');
        e.preventDefault();
        Swal.fire(
            {
            title: "Diqqat",
            text: "Bu kategoriyani o'chirib yubormoqchimisiz?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Xa",
            cancelButtonText: "Yo'q",
            backdrop: `
                rgba(16,196,105,.25)
                left top
                no-repeat
              `
            }
        ).then(function(result){
            if (result.value) {
                $.ajax({
                    type: 'GET',
                    url: access_url,
                    success: function (response) {
                        Swal.fire({
                            title: "Bararildi!",
                            text: "Tanlangan kategoriya o'chirib yuborildi!",
                            type: "success",
                            showConfirmButton: false,
                            timer: 1500
                        });
                        setTimeout(function() { window.location.href = response.url; }, 1500);
                    },
                    error: function (error) {
                        Swal.fire("Xato", "Tanlangan kategoriya o'chirilmadi!", "error")
                    }
                })
            }
        })
    });
</script>
{% endblock javascript %}