bot/urls.py
from django.urls import path
from bot import views

urlpatterns = [
    path("list/", views.telegram_user_list, name="telegram-user-list"),
    path("data/list/", views.telegram_user_data_list, name="telegram-user-data-list"),
    path("<int:pk>/activation/", views.telegram_user_activation, name="telegram-user-activation"),
    path("<int:pk>/detail/", views.telegram_user_detail, name="telegram-user-detail"),
]

core/urls.py
from django.conf.urls import include
from django.urls import path
from core import views
from category import urls as category_urls
from product import urls as product_urls
from bot import urls as telegram_user_urls
from order import urls as order_urls

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("login/", views.dashboard_login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("category/", include(category_urls)),
    path("product/", include(product_urls)),
    path("telegram-user/", include(telegram_user_urls)),
    path("order/", include(order_urls)),
]

fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models


class Notification(models.Model):
    user_sender = models.ForeignKey(User, null=True, blank=True, related_name='user_sender', on_delete=models.CASCADE)
    user_revoker = models.ForeignKey(User, null=True, blank=True, related_name='user_revoker', on_delete=models.CASCADE)
    status = models.CharField(max_length=264, null=True, blank=True, default="unread")
    type_of_notification = models.CharField(max_length=264, null=True, blank=True)

templates/telegram_user/list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'js/plugins/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card p-3">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-10"><h5 class="mb-0">Foydalanuvchilar</h5></div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-flush" id="datatable-basic">
                                <form method="GET">
                                    <thead>
                                        <tr>
                                            <th class="align-middle text-center" colspan="4">
                                                <input type="text" id="id_search" name="search" class="form-control form-control-sm" value="{{ search }}" placeholder="Qidirish ...">
                                            </th>
                                            <th class="align-middle text-center" colspan="1" >
                                            </th>
                                            <th class="align-middle text-center" colspan="1">
                                                <button type="submit" class="btn btn-primary btn-sm font-weight-bold text-xs" style="margin: 0 !important;"><i class="fas fa-filter"> </i><span> Фильтровать </span></button>
                                            </th>
                                        </tr>
                                    </thead>
                                </form>
                                <thead class="thead-light">
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Chat ID
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Ism
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Familiya
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Telefon raqam
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7">
                                        Aktiv
                                    </th>
                                    <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for telegram_user in telegram_users %}
                                <tr>
                                    <td class="text-sm font-weight-normal"><div style="margin-left:1rem;">{{ telegram_user.chat_id }}</div></td>
                                    <td class="text-sm text-center font-weight-normal">{{ telegram_user.first_name }}</td>
                                    <td class="text-sm text-center font-weight-normal">{{ telegram_user.last_name }}</td>
                                    <td class="text-sm text-center font-weight-normal">{{ telegram_user.phone_number }}</td>
                                    <td class="text-sm text-center font-weight-normal">{% if telegram_user.is_active %}<span class="badge bg-gradient-success">Xa</span>{% else %}<span class="badge bg-gradient-danger">Yo'q</span>{% endif %} </td>
                                    <td class="text-sm text-center font-weight-normal">
                                        <a href="{% url 'dashboard:telegram-user-detail' pk=telegram_user.chat_id %}" class="badge badge-sm bg-gradient-warning font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Batafsil">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="{% url 'dashboard:telegram-user-activation' pk=telegram_user.chat_id %}" class="faq-delete badge badge-sm bg-gradient-danger font-weight-bold text-xs" data-action={% if telegram_user.is_active %}true{% else %}false{% endif %} data-toggle="tooltip" data-original-title="O'chirib tashlash">
                                            <i class="fas fa-ban"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
    $(".faq-delete").click(function(e){
        var access_url = $(this).attr('href');
        var status = $(this).attr('data-action');
        if (status == "true"){
            var text_extra1 = "bloklamoqchimisiz";
            var text_extra2 = "bloklandi";
            var text_extra3 = "bloklanmadi";
        }else{
            var text_extra1 = "aktivlashtirmoqchimisiz";
            var text_extra2 = "aktivlashtirildi";
            var text_extra3 = "aktivlashtirilmadi";
        }
        e.preventDefault();
        Swal.fire(
            {
            title: "Diqqat",
            text: "Bu foydalanuvchini " + text_extra1 + "?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Xa",
            cancelButtonText: "Yo'q",
            backdrop: `
                rgba(16,196,105,.25)
                left top
                no-repeat
              `
            }
        ).then(function(result){
            if (result.value) {
                $.ajax({
                    type: 'GET',
                    url: access_url,
                    success: function (response) {
                        Swal.fire({
                            title: "Bajarildi!",
                            text: "Beldilangan foydalanuvchi " + text_extra2 + "!",
                            type: "success",
                            showConfirmButton: false,
                            timer: 1500
                        });
                        setTimeout(function() { window.location.href = response.url; }, 1500);
                    },
                    error: function (error) {
                        Swal.fire("Xato", "Beldilangan foydalanuvchi " + text_extra3 + "!", "error")
                    }
                })
            }
        })
    });
</script>
{% endblock javascript %}

templates/telegram_user/view.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card">
                    <div class="card-header" style="padding: 15px;">
                        <div class="col-md-12">
                            <h5 class="">Foyanlanuvchi: {{ model.first_name }} {{ model.last_name }}</h5>
                        </div>
                    </div>
                    <div class="card-body" style="padding: 5px;">
                        {% for order in orders %}
                        <hr>
                        <div class="row">
                            <div class="col-lg-4">
                                <h5 class="mb-4">Buyurtma №{{ order.id }}</h5>
                                <h6 class="mb-4">Umumiy malumot</h6>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Status:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ order.get_status_display }}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Izoh:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{% if order.comment %}{{ order.comment }}{% else %}Yo'q{% endif %}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Telefon raqam:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ order.phone_number }}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Manzil:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">
                                        <a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{ order.latitude }},{{ order.longitude }}">
                                            <span class="mr-2">Google Maps</span>
                                            <i class="fas fa-map-pin"></i>
                                        </a>
                                    </span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Qo'shilgan vaqti:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ order.created_at|date:'H:i d-m-Y' }}</span>
                                </div>
                                <br>
                                <h6 class="mb-4">Mahsulotlar va narxlar</h6>
                                {% for op in order|order_products %}
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    {{ op.product.name }}
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ op.amount }} x {{ op.price_per_one }} won</span>
                                </div>
                                {% endfor %}
                                <div class="d-flex justify-content-between mt-4">
                                    <span class="mb-2 text-sm">
                                    Mahsulotlar narxi:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ order.total_price|subtract:order.delivery_price }} won</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Yetkazib berish narxi:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ order.delivery_price }} won</span>
                                </div>
                                <div class="d-flex justify-content-between mt-4">
                                    <span class="mb-2 text-md">
                                    Umumiy:
                                    </span>
                                    <span class="text-dark text-md ms-2 font-weight-bold">{{ order.total_price }} won</span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}