bot/urls.py
from django.urls import path
from bot import views

urlpatterns = [
    path("list/", views.telegram_user_list, name="telegram-user-list"),
    path("data/list/", views.telegram_user_data_list, name="telegram-user-data-list"),
    path("<int:pk>/activation/", views.telegram_user_activation, name="telegram-user-activation"),
    path("<int:pk>/detail/", views.telegram_user_detail, name="telegram-user-detail"),
]

core/urls.py
from django.conf.urls import include
from django.urls import path
from core import views
from category import urls as category_urls
from product import urls as product_urls
from bot import urls as telegram_user_urls
from order import urls as order_urls

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("login/", views.dashboard_login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("category/", include(category_urls)),
    path("product/", include(product_urls)),
    path("telegram-user/", include(telegram_user_urls)),
    path("order/", include(order_urls)),
]

fastfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

urlpatterns = [
    path("list/", views.order_list, name="order-list"),
    path("<int:pk>/edit/", views.order_edit, name="order-edit"),
    path("<int:pk>/chat/", views.order_chat, name="order-chat"),
    path("<int:pk>/map/", views.order_map, name="order-map"),
]

order/models.py
from django.db import models

from order.choices import OrderStatus, OrderType
from product.models import Product


class Order(models.Model):
    telegram_user = models.ForeignKey("bot.TelegramUser", on_delete=models.PROTECT)
    products = models.ManyToManyField("product.Product", through="OrderProduct")
    comment = models.TextField(blank=True)
    phone_number = models.CharField(max_length=50)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    delivery_price = models.BigIntegerField(default=0)
    total_price = models.BigIntegerField(default=0)
    status = models.CharField(max_length=255, choices=OrderStatus.choices, default=OrderStatus.PENDING)
    order_type = models.CharField(max_length=255, choices=OrderType.choices, default=OrderType.DELIVERY)
    takeaway_time = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    delivered_at = models.DateTimeField(null=True)


class OrderProduct(models.Model):
    order = models.ForeignKey("order.Order", on_delete=models.PROTECT)
    product = models.ForeignKey("product.Product", on_delete=models.PROTECT)
    amount = models.PositiveIntegerField()
    price_per_one = models.PositiveIntegerField(default=0)

order/forms.py
from order.choices import OrderStatus
from order.models import Order
from django import forms


class OrderChatForm(forms.Form):
    text = forms.CharField(
        max_length=255,
        label="Xabar",
        widget=forms.Textarea(attrs={"class": "form-control", "row": 5}),
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("status", )
        labels = {
            "status": "Status",
        }
        widgets = {
            "status": forms.Select(attrs={"class": "form-control"}),
        }

    def save(self, commit=True, *args, **kwargs):
        old_status = kwargs.get("old_status")
        model = super().save(commit=False)
        if commit:
            allowed_changes = get_allowed_status_changes(status=old_status, order_type=model.order_type)
            if model.status in allowed_changes:
                model.save()
            else:
                model = None
        return model


def get_allowed_status_changes(status, order_type):
    if order_type == "delivery":
        status_change_map = {
            OrderStatus.PENDING.value: [OrderStatus.DENIED.value, OrderStatus.PREPARING.value],
            OrderStatus.PREPARING.value: [OrderStatus.DENIED.value, OrderStatus.PREPARED.value],
            OrderStatus.PREPARED.value: [OrderStatus.DENIED.value, OrderStatus.DELIVERING.value],
            OrderStatus.DELIVERING.value: [OrderStatus.DENIED.value, OrderStatus.DELIVERED.value],
        }
    else:
        status_change_map = {
            OrderStatus.PENDING.value: [OrderStatus.DENIED.value, OrderStatus.PREPARING.value],
            OrderStatus.PREPARING.value: [OrderStatus.DENIED.value, OrderStatus.PREPARED.value],
            OrderStatus.PREPARED.value: [OrderStatus.DENIED.value, OrderStatus.DELIVERED.value],
        }
    return status_change_map.get(status, [])

order/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.core.paginator import Paginator
from django.template.response import TemplateResponse
from django.http.response import JsonResponse
from telegram import bot

from order.choices import OrderStatus
from order.models import Order, OrderProduct
from order.forms import OrderForm, OrderChatForm
from django.shortcuts import redirect, get_object_or_404, reverse
from core.views import login_required


@login_required
def order_list(request):
    page = int(request.GET.get("page", 1))
    per_page = int(request.GET.get("per_page", 15))
    status = request.GET.get("status", "")
    orders = Order.objects.all().order_by("-created_at")
    if status:
        orders = orders.filter(status=status)

    paginator = Paginator(orders, per_page)
    orders = paginator.page(page)
    context = {
        "orders": orders,
        "per_page": per_page,
        "status": status
    }
    return TemplateResponse(request, "order/list.html", context)


@login_required
def order_edit(request, pk=None):
    model = Order.objects.get(pk=pk)
    order_products = OrderProduct.objects.filter(order=model)
    old_status = model.status
    form = OrderForm(request.POST or None, instance=model)
    message = ""
    if request.POST:
        if form.is_valid():
            res = form.save(old_status=old_status)
            if res:
                msg = get_status_message(status=res.status)
                msg = msg.format(res.id)
                bot.Bot(token=settings.BOT_TOKEN).send_message(
                    chat_id=res.telegram_user.chat_id,
                    text=msg,
                    parse_mode="HTML"
                )
                return redirect("dashboard:order-list")
            else:
                message = f"{model.get_status_display()} ga o'zgartirib bolmaydi! Ketma-ketlikni to'g'ri amalga oshiring!"
        else:
            print(form.errors)
    context = {
        "model": model,
        "form": form,
        "message": message,
        "order_products": order_products
    }
    return TemplateResponse(request, "order/form.html", context)


@login_required
def order_chat(request, pk=None):
    model = Order.objects.get(pk=pk)
    form = OrderChatForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            msg = form.cleaned_data.get("text", "")
            bot.Bot(token=settings.BOT_TOKEN).send_message(
                chat_id=model.telegram_user.chat_id,
                text=msg,
                parse_mode="HTML"
            )
            return redirect("dashboard:order-list")
        else:
            print(form.errors)
    context = {
        "model": model,
        "form": form,
    }
    return TemplateResponse(request, "order/chat.html", context)


@login_required
def order_map(request, pk=None):
    model = Order.objects.get(pk=pk)
    context = {
        "model": model,
        "KAKAO_MAP_APP_KEY": settings.KAKAO_MAP_APP_KEY,
    }
    return TemplateResponse(request, "order/map.html", context)


def get_status_message(status):
    status_change_map = {
        OrderStatus.DENIED.value: "<b>Buyurtmangiz №{} bekor qilindi!</b>",
        OrderStatus.PREPARING.value: "<b>Buyurtmangiz  №{} tayyorlanish jarayonida!</b>",
        OrderStatus.PREPARED.value: "<b>Buyurtmangiz  №{} tayyor!</b>",
        OrderStatus.DELIVERING.value: "<b>Buyurtmangiz  №{} yetkazib berish jarayonida! 20 daqiqa ichida yetkazib beriladi!</b>",
        OrderStatus.DELIVERED.value: "<b>Buyurtmangiz  №{} topshirildi. Yoqibli ishtaha!</b>",
    }
    return status_change_map.get(status, "")



templates/order/form.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card">
                    <div class="card-header" style="padding: 15px;">
                        <div class="col-md-12">
                            <div class="toast fade hide p-2 mt-2 bg-white" role="alert" aria-live="assertive"
                                 id="dangerToast" aria-atomic="true">
                                <div class="toast-header border-0">
                                    <i class="ni ni-notification-70 text-danger me-2"></i>
                                    <span class="me-auto text-gradient text-danger font-weight-bold">Status</span>
                                    <i class="fas fa-times text-md ms-3 cursor-pointer" data-bs-dismiss="toast"
                                       aria-label="Close"></i>
                                </div>
                                <hr class="horizontal dark m-0">
                                <div class="toast-body">
                                    {{ message }}
                                </div>
                            </div>
                            <h5 class="">Buyurtma №{{ model.id }}</h5>
                        </div>
                    </div>
                    <div class="card-body" style="padding: 5px;">
                        <div class="row">
                            <div class="col-lg-4">
                                <h6 class="mb-4">Umumiy malumot</h6>
                                <div class="d-flex justify-content-between mt-4">
                                    <span class="mb-2 text-sm">
                                    Buyurtmachi:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ model.telegram_user.first_name }} {{ model.telegram_user.last_name }}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Izoh:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{% if model.comment %}{{ model.comment }}{% else %}Yo'q{% endif %}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Turi:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ model.get_order_type_display }}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Telefon raqam:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ model.phone_number }}</span>
                                </div>
                                {% if model.order_type == "delivery" %}
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Manzil:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">
                                        <a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{ model.latitude }},{{ model.longitude }}"> Google Maps </a>
                                        <a target="_blank" href="{% url 'dashboard:order-map' pk=model.id %}"> Kakao Maps </a>
                                    </span>
                                </div>
                                {% else %}
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Olib ketish vaqti:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ model.takeaway_time }} minutdan keyin</span>
                                </div>
                                {% endif %}
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Qo'shilgan vaqti:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ model.created_at|date:'H:i d-m-Y' }}</span>
                                </div>
                                <br>
                                <h6 class="mb-4">Mahsulotlar va narxlar</h6>
                                {% for op in order_products %}
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    {{ op.product.category.name }} {{ op.product.name }}
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ op.amount }} x {{ op.price_per_one }} won</span>
                                </div>
                                {% endfor %}
                                <div class="d-flex justify-content-between mt-4">
                                    <span class="mb-2 text-sm">
                                    Mahsulotlar narxi:
                                    </span>
                                    <span class="text-dark font-weight-bold ms-2">{{ model.total_price|subtract:model.delivery_price }} won</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="mb-2 text-sm">
                                    Yetkazib berish narxi:
                                    </span>
                                    <span class="text-dark ms-2 font-weight-bold">{{ model.delivery_price }} won</span>
                                </div>
                                <div class="d-flex justify-content-between mt-4">
                                    <span class="mb-2 text-md">
                                    Umumiy:
                                    </span>
                                    <span class="text-dark text-md ms-2 font-weight-bold">{{ model.total_price }} won</span>
                                </div>
                            </div>
                        </div>
                        <br>
                        <form method="post" autocomplete=off enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        {{ form.status.errors }}
                                        <label class="form-control-label" for="{{ form.status.id_for_label }}">{{ form.status.label }}</label>
                                        {{ form.status }}
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group text-left mb-0">
                                        <div class="col-lg-3 col-sm-6 col-12 mt-lg-0 mt-2">
                                          <button class="btn btn-danger w-100 mb-0 toast-btn" style="display: none;" id="idAlertTrigger" type="button" data-target="dangerToast"></button>
                                        </div>
                                        {% if model %}
                                        <button class="btn btn-warning waves-effect waves-light mr-1" type="submit">
                                            Saqlash
                                        </button>
                                        {% endif %}
                                        <a href="{% url 'dashboard:order-list' %}" class="btn btn-danger waves-effect waves-light">
                                            Bekor qilish
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
<script>
    var msg = "{{ message }}";
    if (msg != ""){
        $(document).ready(function(){
            $( "#idAlertTrigger" ).trigger( "click" );
        });
    }
</script>
{% endblock javascript %}

templates/order/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-10"><h5 class="mb-0">Buyurtmalar</h5></div>
                            <div class="col-md-2 mx-auto">
                                <form method="get">
                                    <div class="form-group">
                                        <label for="id_order_status_filter">Status</label>
                                        <select name="status" class="form-control" id="id_order_status_filter" onchange="this.form.submit()">
                                            <option value="" {% if status == '' %}selected{% endif %}>Hammasi</option>
                                            <option value="pending" {% if status == 'pending' %}selected{% endif %}>Kutilmoqda</option>
                                            <option value="denied" {% if status == 'denied' %}selected{% endif %}>Bekor qilingan</option>
                                            <option value="preparing" {% if status == 'preparing' %}selected{% endif %}>Tayyorlanmoqda</option>
                                            <option value="prepared" {% if status == 'prepared' %}selected{% endif %}>Tayyor</option>
                                            <option value="delivering" {% if status == 'delivering' %}selected{% endif %}>Kuryerda</option>
                                            <option value="delivered" {% if status == 'delivered' %}selected{% endif %}>Buyurtma topshirildi</option>
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="card-body" id="id_orders_list">
                        {% for order in orders %}
                        <div class="card mb-3">
                            <div class="card-body">
                                {% if order.status == 'pending' %}
                                <span class="badge bg-gradient-primary">{{ order.get_status_display}}</span>
                                {% elif order.status == 'denied' %}
                                <span class="badge bg-gradient-danger">{{ order.get_status_display}}</span>
                                {% elif order.status == 'preparing' %}
                                <span class="badge bg-gradient-warning">{{ order.get_status_display}}</span>
                                {% elif order.status == 'prepared' %}
                                <span class="badge bg-gradient-warning">{{ order.get_status_display}}</span>
                                {% elif order.status == 'delivering' %}
                                <span class="badge bg-gradient-warning">{{ order.get_status_display}}</span>
                                {% elif order.status == 'delivered' %}
                                <span class="badge bg-gradient-success">{{ order.get_status_display}}</span>
                                {% endif %}
                                <span class="badge bg-gradient-success">
                                    {% if order.order_type == "delivery" %}
                                    <i class="fas fa-car-side"></i>
                                    {% elif order.order_type == "take_away" %}
                                    <i class="fas fa-walking"></i>
                                    {% endif %}
                                </span>
                                <h6 class="card-title mb-0">Buyurtma № {{ order.id }}</h6>
                                <p class="text-muted">{{ order.phone_number }}</p>
                                <a href="{% url 'dashboard:order-edit' pk=order.id %}" class="btn btn-warning">Batafsil</a>
                                <a href="{% url 'dashboard:order-chat' pk=order.id %}" class="btn btn-icon btn-2 btn-primary">
                                    <span class="btn-inner--icon"><i class="ni ni-chat-round"></i></span>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <div class="pagination-container justify-content-end mt-4">
                            <ul class="pagination pagination-success">
                                <li class="page-item {% if not orders.has_previous %}disabled{% endif %}">
                                    <a class="page-link with-prev-row" href="" data-action="{% if orders.has_previous %}?page={{ orders.previous_page_number }}{% endif %}" aria-label="Previous">
                                        <span aria-hidden="true"><i class="fa fa-angle-left" aria-hidden="true"></i></span>
                                    </a>
                                </li>

                                {% for i in orders.paginator.page_range %}
                                    {% if orders.number > 5 and forloop.first %}
                                        <li class="page-item">
                                            <a class="page-link page-number" href="" data-action="1">1</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link page-number" href="" data-action="2">2</a>
                                        </li>
                                        <li class="page-item disabled">
                                          <a class="page-link page-number" href="" data-action="">...</a>
                                        </li>
                                    {% endif %}
                                    {% if orders.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link page-number" href="" data-action="{{ i }}">{{ i }}</a>
                                        </li>
                                    {% elif i > orders.number|add:'-5' and i < orders.number|add:'5' %}
                                        <li class="page-item">
                                            <a class="page-link page-number" href="" data-action="{{ i }}">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                    {% if orders.paginator.num_pages > orders.number|add:'5' and forloop.last %}
                                        <li class="page-item page-item">
                                            <a class="page-link page-number" href="" data-action="">...</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link page-number" href="" data-action="{{ orders.paginator.num_pages|add:'-1' }}">{{ orders.paginator.num_pages|add:'-1' }}</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link page-number" href="" data-action="{{ orders.paginator.num_pages }}">{{ orders.paginator.num_pages }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                <li class="page-item {% if not orders.has_next %}disabled{% endif %}">
                                    <a class="page-link with-next-row" href="" data-action="{% if orders.has_next %}?page={{ orders.next_page_number }}{% endif %}" aria-label="Next">
                                        <span aria-hidden="true"><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
<script>
    $(".faq-delete").click(function(e){
        var access_url = $(this).attr('href');
        e.preventDefault();
        Swal.fire(
            {
            title: "Diqqat",
            text: "Bu mahsulotni o'chirib yubormoqchimisiz?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Xa",
            cancelButtonText: "Yo'q",
            backdrop: `
                rgba(16,196,105,.25)
                left top
                no-repeat
              `
            }
        ).then(function(result){
            if (result.value) {
                $.ajax({
                    type: 'GET',
                    url: access_url,
                    success: function (response) {
                        Swal.fire({
                            title: "Bararildi!",
                            text: "Tanlangan mahsulot ochirib yuborildi o'chirib yuborildi!",
                            type: "success",
                            showConfirmButton: false,
                            timer: 1500
                        });
                        setTimeout(function() { window.location.href = response.url; }, 1500);
                    },
                    error: function (error) {
                        Swal.fire("Xato", "Tanlangan mahsulot o'chirilmadi!", "error")
                    }
                })
            }
        })
    });
</script>
<script>
    console.log("Creating web socket");
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/order/list/notification/'
    );
    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        var status_badge = ""
        if(data.data.status == 'pending'){
            status_badge = '<span class="badge bg-gradient-primary">' + data.data.status_label +'</span>'
        }else if(data.data.status == 'denied'){
            status_badge = '<span class="badge bg-gradient-danger">' + data.data.status_label +'</span>'
        }else if(data.data.status == 'preparing'){
            status_badge = '<span class="badge bg-gradient-warning">' + data.data.status_label +'</span>'
        }else if(data.data.status == 'prepared'){
            status_badge = '<span class="badge bg-gradient-warning">' + data.data.status_label +'</span>'
        }else if(data.data.status == 'delivering'){
            status_badge = '<span class="badge bg-gradient-warning">' + data.data.status_label +'</span>'
        }else if(data.data.status == 'delivered'){
            status_badge = '<span class="badge bg-gradient-success">' + data.data.status_label +'</span>'
        }

        var order_type = ""
        if(data.data.order_type == 'delivery'){
            order_type = '<span class="badge bg-gradient-success"><i class="fas fa-car-side"></i></span>'
        }else if(data.data.order_type == 'take_away'){
            order_type = '<span class="badge bg-gradient-success"><i class="fas fa-walking"></i></span>'
        }
        var child = `<div class="card mb-3">
            <div class="card-body">` + status_badge + order_type + `<h6 class="card-title mb-0">Buyurtma № ` + data.data.id + `</h6>
            <p class="text-muted">` + data.data.phone_number + `</p>
            <a href="/order/` + data.data.id + `/edit/" class="btn btn-warning">Batafsil</a>
            <a href="/order/` + data.data.id + `/chat/" class="btn btn-icon btn-2 btn-primary"><span class="btn-inner--icon"><i class="ni ni-chat-round"></i></span></a>
            </div>
        </div>`
        $("#id_orders_list").prepend(child);
    };
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

</script>
<script>
    function filterPage(addToPage){
        var status = $("#id_order_status_filter option:selected").val();
        var page = parseInt($("li.page-item.active a.page-link").html()) + addToPage;

        const urlParams = new URLSearchParams(window.location.search);

        urlParams.set('status', status);
        urlParams.set('per_page', 15);
        urlParams.set('page', page);

        window.location.search = urlParams;
    }
    $("a.page-link.page-number").click(function(e){
        e.preventDefault();
        var page = parseInt($(this).html());
        if (parseInt($("li.page-item.active a.page-link").html()) != page){
            filterPage(page - parseInt($("li.page-item.active a.page-link").html()));
        }
    });
    $("a.page-link.with-next-row").click(function(e){
        e.preventDefault();
        filterPage(1);
    });
    $("a.page-link.with-prev-row").click(function(e){
        e.preventDefault();
        filterPage(-1);
    });
</script>
{% endblock javascript %}